create database python_project;
use python_project;
CREATE TABLE STUDENT (
    STUDENT_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(20) default NULL,
    LAST_NAME VARCHAR(20) default NULL,
    DATE_OF_BIRTH DATE,
    EMAIL VARCHAR(30)
);
CREATE TABLE COURSES (
    COURSE_ID INT PRIMARY KEY,
    COURSE_NAME VARCHAR(15),
    START_DATE DATE,
    END_DATE DATE,
    CREDIT INT
);
CREATE TABLE GRADES(
    GRADE CHAR(3),
    MARKS INT,
    STUDENT_ID INT,
    COURSE_ID INT,
    FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY(COURSE_ID) REFERENCES COURSES(COURSE_ID)
);
